# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 8, 55, 41, 943463, tzinfo=utc), verbose_name='date published'),
        ),
    ]
